spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/b_account
    username: root
    password: Teja@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082